CREATE TABLE TB_PAYMENT (
  PAYMENT_CODE VARCHAR(50) NOT NULL,
  USER_ID VARCHAR(50) NOT NULL,
  PAYMENT_DESCRIPTION VARCHAR(255) NOT NULL,
  REFERENCE_NUMBER VARCHAR(255) NOT NULL,
  PAYMENT_DATE DATETIME NOT NULL,
  AMOUNT DECIMAL(10,2) NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TB_PAYMENT ADD PRIMARY KEY(PAYMENT_CODE);

${onlyMySQLStart}
alter table TB_PAYMENT CHANGE UPDATE_DATE UPDATE_DATE DATETIME ON update CURRENT_TIMESTAMP;
${onlyMySQLEnd}
